
Vagrant.configure("2") do |config|

  config.vm.synced_folder "/home/Student/vagrant/lab2/source", "/mnt", owner: "vagrant", group: "vagrant", create: true
  config.vm.box = "mntlab"
  config.vm.box_url = "mntlab20160711.box"
  config.vm.provision "shell", path: "fixvm.sh"
  config.vm.network "private_network", ip: "192.168.56.10"

end
